#include "farversion.hpp"

#define PLUGIN_BUILD 0
#define PLUGIN_DESC L"IBSO 32-bit Plugin for Far Manager"
#define PLUGIN_NAME L"IBSOx32"
#define PLUGIN_FILENAME L"IBSOx32.dll"
#define PLUGIN_AUTHOR L"SirYouGin@gmail.com"
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
